MazeG1/WebApplication/Models/CalcViewModel.cs
using Microsoft.AspNetCore.Components.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.DbStuff.Model;

namespace WebApplication.Models
{
    public class CalcViewModel
    {
        public Oper Operation { get; set; }
        public float Number1 { get; set; }
        public float Number2 { get; set; }
        public float Answer { get; set; }
        public List<CalcHistoryViewModel> CalcHistory { get; set; }
    }
}

MazeG1/WebApplication/Controllers/CalcController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication.DbStuff;
using WebApplication.DbStuff.Model;
using WebApplication.DbStuff.Repository;
using WebApplication.Models;
using WebApplication.Presentation;
using WebApplication.Service;

namespace WebApplication.Controllers
{
    public class CalcController : Controller
    {
        private CalcPresentation _calcPresentation;
        private FiletoPDF _filetoPDF;

        public CalcController(CalcPresentation calcPresentation,
            FiletoPDF filetoPDF)
        {
            _calcPresentation = calcPresentation;
            _filetoPDF = filetoPDF;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = _calcPresentation.GetCalcViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(CalcViewModel calcViewModel)
        {
            var model = _calcPresentation.GetCalcViewModel(calcViewModel);
            return View(model);
        }


        public IActionResult UserDoSome(int num1, int num2)
        {
            var model = new CalcViewModel() { 
                Answer = num1 + num2
            };

            return Json(model);
        }

        public IActionResult Calculate(int num1, int num2, int operation)
        {
            var model = _calcPresentation.GetCalcHistory(num1, num2, operation);
            return Json(model);
        }

        public ActionResult DeleteTableHist()
        {
            _calcPresentation.Clear();
            return Redirect("~/Calc/Index");
        }

        public ActionResult DownloadPDF()
        {
            //сохранение существующего файла с компьютера
            var path = _filetoPDF.GetDefaultFile();

            return PhysicalFile(path,
               "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
               $"FilePDF.pdf"); //почему название файла не берется? :(
        }
   

       public ActionResult TableToPDF()
       {
            //сохранение таблицы в файл
            var model = _calcPresentation.GetViewModelForPDF();
            var path = _filetoPDF.GenerateHistory(model);

       return PhysicalFile(path,
           "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
           $"CalcHistory.docx");
        }

    }
}

MazeG1/WebApplication/Views/Calc/Index.cshtml
@model CalcViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    <script src="~/js/calc.js"></script>
}

<div class="calcIndex">
    <div>
        Калькуляторы
    </div>

    <div class="spoiler">
        <div class="header">
            Убийца...
        </div>
        <div class="content">
            Дворцекий
        </div>
    </div>

    <div>
        <div class="calcNast">
            <form action="Index" method="post">
                <div class="number">Введите 1-ое число: @Html.TextBoxFor(x => @Model.Number1)</div>
                <div class="number">Bведите 2-ое число: @Html.TextBoxFor(x => @Model.Number2)</div>
                <div>
                    Выберите операцию:
                    <select name="Operation">
                        <option value="0">Разделить</option>
                        <option value="1">Умножить </option>
                        <option value="2">Сложить</option>
                        <option value="3">Отнять</option>
                    </select>
                </div>
                <input type="submit" value="Равно" class="GetResult" />

                @*<input type="button" value="Пустышка" class="fun" />*@

                @*<input type="button" value="Отправить AJAX запрос" class="send" />*@

                <input type="button" value="РавноAJAX" class="GetResultAjax" />
                <hr>

                <input type="button" value="Очистить таблицу AJAX" class="clearTable" />

                <hr />
                <input type="button" value="Загрузить таблицу в Docx" onclick="location.href='@Url.Action("TableToPDF", "Calc")'" />



            </form>
        </div>
        <hr>
        <div>Результат: <span class="answer">@Model.Answer</span></div>
    </div>

    <div class="table-calc">
        <table class="calcHistoryTable">
            <tbody>
                <tr class="tableHeader">
                    <td>Номер</td>
                    <td>Введеное 1-е число</td>
                    <td>Введеное 2-е число</td>
                    <td>Операция</td>
                    <td>Результат</td>
                </tr>

                @{
                    var index = 1;
                }
                @foreach (var history in Model.CalcHistory)
                {
                    <tr>
                        <td><p>@(index++)</p></td>
                        <td><p>@history.Number1</p></td>
                        <td><p>@history.Number2</p></td>
                        <td><p>@history.Operation</p></td>
                        <td><p>@history.Answer</p></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>